on:
  schedule: 
    - cron: "55 23 * * 0"
    
jobs:
  traffic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        ref: "traffic"
    
    - name: GitHub traffic 
      uses: sangonzal/repository-traffic-action@v.0.1.6
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
     
    - name: Commit changes
      uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
      with:
        author_name: Traffic Bot
        message: "GitHub traffic"
        add: "./traffic/*"
        ref: "traffic"  # commits to branch "traffic"
